### ISSUE TITLE
Name collision in mobility.cpp

### ISSUE THREAD

**Issue by AlpNov** [BCLab-UNM/Swarmathon-ROS#14]
I tried to define a custom message type in mobility.cpp, however the message is in the namespace "mobility" and there was already a variable of type geometry_msgs::Twist in the file with the name mobility.

Suggest to change the variable to something else.

**Comment by jhecker** [comment]
Hi An, thanks for your suggestion. Unfortunately, as with your previous pull request for an additional option in the simulation, we're not accepting any new modifications from users outside of the development team at this time.

As before, it's always helpful if you can document your suggestions so that we might be able to include them in a future release.

**Comment by AlpNov** [comment]
This isn't a request for additional feature, the ability to use custom messages is a fundamental part of learning and using ROS. Naming a variable so that it collides with the package's namespace, accidentally or intentionally, is a basic bug that should be easily and immediately fixed.

**Comment by jhecker** [comment]
I understand now, my apologies for missing it before. This bug has now been squashed with hotfix-0.5.8 (b1f9b1563691eed7ff12aa037845354e85a5f5aa). Please let me know if you encounter any further issues with namespace collisions.
