### ISSUE TITLE
Pushing Code to Private Repository

### ISSUE THREAD

**Issue by abentleym** [BCLab-UNM/Swarmathon-ROS#20]
I'm trying to follow the command line instructions so that I can push code to the Morehouse College repository, but I get errors:

alexander@alexander-Lenovo-Yoga-2-Pro:~/rover_workspace$ git commit -m "first commit"
**Please tell me who you are.**

**Run**

**git config --global user.email "you@example.com"**
**git config --global user.name "Your Name"**

**to set your account's default identity.**
**Omit --global to set the identity only in this repository.((**

**fatal: unable to auto-detect email address (got 'alexander@alexander-Lenovo-Yoga-2-Pro.(none)')**

alexander@alexander-Lenovo-Yoga-2-Pro:~/rover_workspace$ git remote add origin git@github.com:BCLab-UNM/Swarmathon-Morehouse.git
**fatal: remote origin already exists.**

alexander@alexander-Lenovo-Yoga-2-Pro:~/rover_workspace$ git push -u origin master
**Username for 'https://github.com': abentleym
Password for 'https://abentleym@github.com': 
remote: Permission to BCLab-UNM/Swarmathon-ROS.git denied to abentleym.
fatal: unable to access 'https://github.com/BCLab-UNM/Swarmathon-ROS.git/': The requested URL returned error: 403**

**Comment by jhecker** [comment]
You're trying to push code to our Swarmathon-ROS repo, which you don't have write access to, and that's why GitHub is denying your request.

You should use ```git remote set-url origin``` in order to change the origin to your private GitHub repo. In other words, try:

```git remote set-url origin https://github.com/BCLab-UNM/Swarmathon-Morehouse.git```

Additionally, you should set up your ```git``` configuration as the application suggests above. In general, you'll want to consult the [git-scm](https://git-scm.com/) as referenced in the [Swarmathon-ROS README](https://github.com/BCLab-UNM/Swarmathon-ROS)
