### ISSUE TITLE
rqt gui crashing

### ISSUE THREAD

**Issue by jfisher4** [BCLab-UNM/Swarmathon-ROS#29]
I am trying to run the simulation after a fresh install of ros and the swarmathon default code.  After I build the default sim and click on achilles to view the sensor output everything appears to crash. The terminal shows this output when this occurs. Any Ideas? Can this be replicated on your end?

./run.sh: line 17: 25132 Segmentation fault      (core dumped) rqt -s rqt_rover_gui
Cleaning up ROS and Gazebo Processes
killing:
 * /achilles_EKF
 * /achilles_MOBILITY
 * /achilles_NAVSAT
 * /achilles_OBSTACLE
 * /achilles_TARGET
 * /aeneas_EKF
 * /aeneas_MOBILITY
 * /aeneas_NAVSAT
 * /aeneas_OBSTACLE
 * /aeneas_TARGET
 * /ajax_EKF
 * /ajax_MOBILITY
 * /ajax_NAVSAT
 * /ajax_OBSTACLE
 * /ajax_TARGET
 * /gazebo
 * /joy_node
 * /rosout
 * /rqt_gui_cpp_node_25132
[ WARN] [1468267707.234107880]: Shutdown request received.
[ WARN] [1468267707.234179497]: Reason given for shutdown: [user request]
[rosout-1] process has finished cleanly
log file: /home/fish/.ros/log/026270ee-47a3-11e6-a35f-90b11c763b63/rosout-1*.log
[rosout-1] restarting process
process[rosout-1]: started with pid [28243]

Thanks,

Ryan

**Comment by jfisher4** [comment]
This issue should be closed. After wiping my ubuntu installation and starting over this is no longer a problem. However I am experiencing an issue where I an not receiving any simulated GPS data. 
![screenshot from 2016-07-11 20 30 42](https://cloud.githubusercontent.com/assets/10942501/16751359/ddaf1316-47a6-11e6-8b70-794484cec69f.png)

Any Ideas of how I should trouble shoot this?

Thanks,

Ryan

**Comment by jfisher4** [comment]
Also I noticed that the hector gazebo plugins have had some recent updates. Could this perhaps be the source of the problem?

**Comment by jhecker** [comment]
Ryan,

I'm glad you resolved the segfault issue.

Regarding the GPS data, the bug is due to an upgrade to robot_localization v2.2.3 (see [changelog](http://docs.ros.org/kinetic/changelogs/robot_localization/changelog.html) for details) which expects the GPS data to include a transform from the GPS frame_id to the robot's base_link frame.

I just patched the GPS bug in hotfix-0.8.3 (4a930e72ec211d4a032a16f1f75310e606d6e4ef). Let me know if you encounter any other issues with this bug in the future.
